on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dataverse Uploader Action
        # You may pin to the exact commit or the version.
        # uses: IQSS/dataverse-uploader@a91124cbea5f0c5913ca193d5945fc374e71e0eb
        uses: IQSS/dataverse-uploader@v1.1
        with:
          # dataverse personal access token
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          # dataverse server
          DATAVERSE_SERVER: https://borealisdata.ca/
          # existing dataverse dataset doi
          DATAVERSE_DATASET_DOI: doi:10.5683/SP3/WBSFPE
          # only upload data directory
          GITHUB_DIR: data
